import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster";

import Providers from "@/components/Providers";
import "react-loading-skeleton/dist/skeleton.css"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
    <Providers>
    <body  className={cn(
            'min-h-screen font-sans antialiased grainy',
            inter.className
          )}>
            <Toaster/>
            <NavBar/>
        {children}
      </body>
    </Providers>
    </html>
  );
}
